### ISSUE TITLE
How to load the dataset?

### ISSUE THREAD

**Issue by L-hongbin** [mlfoundations/MINT-1T#12]
I have downloaded a file "shard_001_part_001.parquet"，and try to load it:
```
from datasets import load_dataset
mtnt = load_dataset("parquet",data_files="./shard_001_part_001.parquet", cache_dir="./")
```
but got fail:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/datasets/builder.py", line 1853, in _prepare_split_single
    for _, table in generator:
  File "/opt/conda/lib/python3.8/site-packages/datasets/packaged_modules/parquet/parquet.py", line 86, in _generate_tables
    for batch_idx, record_batch in enumerate(
  File "pyarrow/_parquet.pyx", line 1621, in iter_batches
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
OSError: Corrupt snappy compressed data.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/datasets/load.py", line 2096, in load_dataset
    builder_instance.download_and_prepare(
  File "/opt/conda/lib/python3.8/site-packages/datasets/builder.py", line 924, in download_and_prepare
    self._download_and_prepare(
  File "/opt/conda/lib/python3.8/site-packages/datasets/builder.py", line 999, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datasets/builder.py", line 1740, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/opt/conda/lib/python3.8/site-packages/datasets/builder.py", line 1896, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

**Comment by anas-awadalla** [comment]
Thanks for reaching out! We are aware of this issue and are fixing it now. I will update you here when it is fixed.

**Comment by anas-awadalla** [comment]
I have fixed the parquets. Please let me know if you run into any other issues.
